### ISSUE TITLE
Update favicon & app title name

### ISSUE THREAD

**Issue by snrelghgub** [chingu-voyages/v24-geckos-team-02#30]
**Task Description**
Our app's icon & its title name displayed in the browser need be updated. 

**Resources**
- [This](https://icons8.com/icons/set/books-plus) <-- shall help to find a new app icon 
- [This ](https://reactgo.com/react-change-favicon/) <--- shows how to change the icon 
- The app's title name can simply be changed to our app name 'Books Plus' by editing the text within the title> element in our index.html file 

![Screenshot 2020-10-13 21.33.06.png](https://images.zenhubusercontent.com/5cfc745bb261421fbae0e452/70898a0a-eb64-41b0-a487-6bbd451951bf)

**Comment by jdmedlock** [comment]
Suggest basing the favicon on the Logo that Hak is creating

**Comment by snrelghgub** [comment]
closing this issue as this issue was successfully resolved by @Guitarhub786 in PR #43
