### ISSUE TITLE
Display search results

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/v24-geckos-team-02#4]
**User Story Description**
As a End User
I want to see books matching the search criteria displayed in an infinite scroll 
So I can see the book cover thumbnail, title, and author for all matches

**Steps to Follow (optional)**
- [ ] Step #1
- [ ] Step #2
- [ ] Additional steps as necessary

**Additional Considerations**
Any supplemental information including unresolved questions, links to external resources, screenshots, etc.

**Comment by ghost** [comment]
The user will also want to see the publisher for all matches (based on https://github.com/chingu-voyages/soloproject-tier3-bookfinder).

**Comment by Guitarhub786** [comment]
When we say, "infinite scroll".
If there is a 1000 hits, do we literally mean pasting all the results on the users webpage, that could create time, buffer and memory issues.
Or de we mean 'paginate' i.e 10 items per page.

**Comment by ghost** [comment]
@Guitarhub786 More results will be loaded when the page is scrolled to the bottom.
