### ISSUE TITLE
Unable to view favourites after logging in (in mobile view) 

### ISSUE THREAD

**Issue by snrelghgub** [chingu-voyages/v24-geckos-team-02#81]
**Describe the bug**
Unable to view favorites after successfully logging in (in mobile view) 

**To Reproduce**
- ensure you are not logged in 
- go in mobile view where hamburger menu is displayed 
- log in via hamburger menu 
- attempt to access favourites after successful log in
- message displayed is: Please log in to see your favorites

**Expected behavior**
User shall be able to view & access their favourites successfully from a mobile device in mobile view

**Comment by ArunJose** [comment]
This is because no props are passed to `<HamburgerMenu />` in Navbar.jsx. It should be `<HamburgerMenu {...props} />`. Setter for authtoken is being passed in as props which is needed for `<Authentication />` inside `<HamburgerMenu />`

**Comment by snrelghgub** [comment]
hello @ArunJose thanks for taking the time for looking into this issue & reporting the root cause. I'll fix this issue in my current PR #80 instead of creating another PR to resolve this issue & due to our time constraint 👍

**Comment by snrelghgub** [comment]
closing this as this issue was resolved in a commit via PR #80 & due to time constraints. Thanks again @ArunJose for your promptly coordination & assistance on this issue.
